<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_6376fc0abb8b0',
        'title' => 'Footer Options',
        'fields' => array(
            array(
                'key' => 'field_6376fc11fc3a7',
                'label' => 'Footer Logo',
                'name' => 'footer_logo',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'show_in_graphql' => 1,
                'return_format' => 'url',
                'preview_size' => 'full',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_6376fc2cfc3a8',
                'label' => 'Site Description',
                'name' => 'site_description',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'show_in_graphql' => 1,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_6376fc47fc3a9',
                'label' => 'Podcasts Links',
                'name' => 'podcasts _links',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'show_in_graphql' => 1,
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_6376fc6efc3aa',
                        'label' => 'Spotify',
                        'name' => 'spotify',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'show_in_graphql' => 1,
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_6376fc81fc3ab',
                        'label' => 'Apple Podcasts',
                        'name' => 'apple',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'show_in_graphql' => 1,
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_6376fc95fc3ac',
                        'label' => 'Google Podcasts',
                        'name' => 'google_podcasts',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'show_in_graphql' => 1,
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_6376fcdffc3ad',
                'label' => 'Social Media Links',
                'name' => 'social_media_links',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'show_in_graphql' => 1,
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_6376fcfefc3af',
                        'label' => 'Facebook',
                        'name' => 'facebook',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'show_in_graphql' => 1,
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_6376fd0bfc3b0',
                        'label' => 'LinkedIn',
                        'name' => 'linkedin',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'show_in_graphql' => 1,
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_6376fcf0fc3ae',
                        'label' => 'Instagram',
                        'name' => 'instagram',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'show_in_graphql' => 1,
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_6376fd1bfc3b1',
                        'label' => 'Skype',
                        'name' => 'skype',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'show_in_graphql' => 1,
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_6376ff39d40e8',
                'label' => 'Copyright Text',
                'name' => 'copyright_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'show_in_graphql' => 1,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-footer',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 1,
        'show_in_graphql' => 1,
        'graphql_field_name' => 'footerOptions',
        'map_graphql_types_from_location_rules' => 0,
        'graphql_types' => '',
    ));
    
    endif;		